language: python

before_install:
  - sudo apt-get -qq update

install:
  - git clone --recursive https://github.com/pnorman/ogr2osm
  - sudo apt-get install python-gdal python-lxml curl

script:
  - ./mrwa2osm.sh
